name: AWS Lambda academix make_exam Deploy 
on:
  push:
    paths:
      - 'lambda/make_exam/**' # lambdaディレクトリ以下の変更があった場合にトリガーする
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: checkout lambda
        uses: actions/checkout@v3
        with:
          path: workspace

      - name: configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHubActions

      - name: get-caller-identity is allowed to run on role.
        run: aws sts get-caller-identity

      - name: setup-python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      
      - name: install dependencies
        run: |
          cd workspace/lambda/make_exam
          pip install --upgrade pip
          pip install -r requirements.txt -t .

      - name: deploy to AWS Lambda
        run: |
          cd workspace/lambda/make_exam
          find . -type f ! -name 'requirements.txt' -exec zip make_exam.zip {} +
          pip install awscli
          aws s3 cp make_exam.zip s3://lambda--deploy/make_exam.zip
          aws lambda update-function-code --function-name make_exam --s3-bucket lambda--deploy --s3-key make_exam.zip